/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    'company',
    {
      type: 'category',
      label: 'Product',
      items: ['product/attributes','product/category','product/templates','product/taxation','product/departments','product/variants','product/verification'],
    },
    'orders',
    'integrations',
    {
      type: 'category',
      label: 'Subscription',
      items: ['subscription/invoices','subscription/coupons'],
    },
    {
      type: 'category',
      label: 'Communication',
      items: ['communication/reports'],
    },
    {
      type: 'category',
      label: 'Extension',
      items: ['extension/review','extension/collection'],
    },
    {
      type: 'category',
      label: 'Support Center',
      items: ['support-center/configuration','support-center/ticket-listing'],
    },
    {
      type: 'category',
      label: 'Settings',
      items: ['settings/platform','settings/partner'],
    },
    'webhooks',
  ],
};

module.exports = sidebars;
